modLoader="javafml" #mandatory
loaderVersion="[43,)"
license="All rights reserved" # License Schmicense
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
    modId="tflostblocks"
    version="${file.jarVersion}"
    displayName="Twilight Forest: The Lost Blocks"
    # updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/twilight-forest-the-lost-blocks"
    logoFile="icon.png"
    credits="Thanks to the original developers of Twilight Forest."
    authors="Kitteh6660"
    description='''
    Adds certain missing blocks to Twilight Forest.'''

[[dependencies.tflostblocks]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43.2.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.tflostblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tflostblocks]]
    modId="twilightforest"
    mandatory=true
    versionRange="[4.2.1493,)"
    ordering="AFTER"
    side="BOTH"
